
function AN(_1){if(!_1){return;}
this.ENG={"zoom":zIOE,"fade":fIOE,"slide":sIOE};this.engine=this.ENG[_1];if(!this.engine){return;}
this.run=false;this.target=null;this._uME=null;this._uMF=null;this._uWA=null;this.state=0;this.config={};this.config.name=this.engine._name;this.config.h_v=this.engine._maximum||1;this.config.lowest_val=this.engine._minimum||0;this.config.base_step=this.engine.step||0.1;this.config.base_time=this.engine._time||10;this.config.curve=null;this.dpnd=new AA();this.lastReportedValue=0;}
AN.prototype.attachTo=function(_2){this.target=_2;this._uME=(typeof this.target.style.zoom=="string")?true:false;this._uMF=(typeof this.target.filters!="undefined")?true:false;this._uWA=(typeof this.target.style.opacity=="string")?true:false;};AN.prototype.relateTo=function(_3){this.relation=_3;};AN.prototype.detachFrom=function(_4){this.target=null;};AN.prototype.registerStartCallback=function(_5){this.onStartCallback=_5;};AN.prototype.registerCompleteCallback=function(_6){this.onCompleteCallback=_6;};AN.prototype.registerDependant=function(_7){if(this.dpnd===null){return;}
var _8=new AN(this.config.name);_8.dpnd=null;_8.registerStartCallback=null;_8.registerCompleteCallback=null;_8.attachTo(_7);this.dpnd.push(_8);};AN.prototype.registerCurveGenerator=function(_9){this.config.curve=_9;};AN.prototype._start=function(_a){if(!this.engine){return;}
var _b;if(!this.state){_b=true;}else{if(_a){if(this.state==-1){_b=true;}else{if(this.state==1){_b=false;}}}else{if(this.state==1){_b=true;}else{if(this.state==-1){_b=false;}}}}
if(!_b){return;}
this.run=true;this.engine(_a);if(this.dpnd&&this.dpnd.length){var _t=this;this.dpnd.each(function(_d){_d.__parent=_t;_d.run=true;_d.engine(_a);});}};AN.prototype._stop=function(){this.run=false;if(this.dpnd&&this.dpnd.length){this.dpnd.each(function(_e){_e.run=true;});}};function zIOE(_f){var _10=this;if(typeof _10.onStartCallback=="function"){_10.onStartCallback();}
var _11=_10.target;if(!_10._uME){var _12=function(_13){var _14={};var _15=gCP(_13,"width","number");var _16=gCP(_13,"height","number");if(!_15||!_16){var _17=getLayout(_13);}
_14.width=_15?_15:_17.width;_14.height=_16?_16:_17.height;return _14;};if(typeof _10.orig=="undefined"){if(typeof _10.__parent!="undefined"){if(typeof _10.__parent.orig!="undefined"){_10.orig={"width":_10.__parent.orig.width,"height":Math.ceil(_10.__parent.orig.height/_10.__parent.dpnd.length)};}}else{_10.orig=_12(_11);}}
if(_10.dpnd&&!_10.dpnd.length){var _18=_getOwnChildrenOnly(_11);if(_18.length){var _19=["br"];_Ae(_18,function(_1a){if(_Ai(_19,_1a.nodeName.toLowerCase())==-1){_10.registerDependant(_1a);}});}else{_10.dpnd=null;}}}
var _1b=_10.config.base_step;var _1c,f_v,cnd,toAdd,_state;if(_f){_1c=_10.config.lowest_val+_1b;f_v=_10.config.h_v;cnd=function(a,b){return(a<b)?true:false;};toAdd=_1b;_state=1;}else{_1c=_10.config.h_v-_1b;f_v=_10.config.lowest_val+_1b;cnd=function(a,b){return(a>b)?true:false;};toAdd=(-1)*_1b;_state=-1;}
var _21=function(){this.target=_11;};_21.prototype.get=function(){if(_10._uME){return gCP(this.target,"zoom","number");}else{var _22=_12(this.target);var _23=_22.width/_10.orig.width;return _23;}};_21.prototype.set=function(_24){if(_10._uME){this.target.style.zoom=_24;}else{response_width=(_24*_10.orig.width);response_height=(_24*_10.orig.height);this.target.style.width=response_width+"px";this.target.style.height=response_height+"px";var _25=Math.floor(100*_24)+"%";if(typeof _10.origLineHeight=="undefined"){_10.origLineHeight=gCP(this.target,"line-height");}
this.target.style.lineHeight=_25;if(typeof _10.origFontSize=="undefined"){_10.origFontSize=gCP(this.target,"fontsize");}
this.target.style.fontSize=_25;if(_25=="100%"){this.target.style.lineHeight=_10.origLineHeight;this.target.style.fontSize=_10.origFontSize;}
var _26=(_25!="100%")?"rect("+"0px "+Math.round(response_width+2)+"px "+Math.round(response_height+2)+"px "+"0px"+")":"rect(0px 1000px 1000px 0px)";this.target.style.clip=_26;}};var _27=new _21();_27.set(_1c);var _28=function(){if(!_10.run){return;}
var _29=_27.get();if(cnd(_29,f_v)){n_v=_29+toAdd;if(!cnd(f_v,n_v)){_27.set(n_v);var _2a=10;window.setTimeout(function(){_28();},_2a);}else{_27.set(f_v);_11=null;_10.state=_state;if(typeof _10.onCompleteCallback=="function"){_10.onCompleteCallback();}}}};_28();}
zIOE._name="zoom";zIOE._minimum=0.01;zIOE._maximum=1;zIOE._time=10;zIOE.step=0.08;function fIOE(_2b){var _2c=this;if(typeof _2c.onStartCallback=="function"){_2c.onStartCallback();}
var _2d=_2c.target;if(_2c._uMF){this.target.style.filter="";this.target.style.filter="progid:DXImageTransform.Microsoft.Alpha()";this.target.filters.item("DXImageTransform.Microsoft.Alpha").Enabled=true;this.target.filters.item("DXImageTransform.Microsoft.Alpha").Style=0;this.target.filters.item("DXImageTransform.Microsoft.Alpha").Opacity=1;}else{_2d.style.opacity=0.01;}
var _2e=_2c.config.base_step;var _2f,f_v,cnd,toAdd,_state;if(_2b){_2f=_2c.config.lowest_val+_2e;f_v=_2c.config.h_v;cnd=function(a,b){return(a<b)?true:false;};toAdd=_2e;_state=1;}else{_2f=_2c.config.h_v-_2e;f_v=_2c.config.lowest_val+_2e;cnd=function(a,b){return(a>b)?true:false;};toAdd=(-1)*_2e;_state=-1;}
var _34=function(){this.target=_2d;};_34.prototype.get=function(){if(_2c._uMF){try{var _35=this.target.filters.item("DXImageTransform.Microsoft.Alpha").Opacity/100;_2c.lastReportedValue=_35;return _35;}
catch(e){return _2c.lastReportedValue;}}else{if(_2c._uWA){return gCP(this.target,"opacity","number");}
return f_v;}};_34.prototype.set=function(_36){if(_2c._uMF){try{this.target.filters.item("DXImageTransform.Microsoft.Alpha").Opacity=(_36*100);}
catch(e){}
if(_36==1){this.target.style.filter="";}}else{if(_2c._uWA){this.target.style.opacity=_36;}}};var _37=new _34();var _38=function(){if(!_2c.run){return;}
var _39=_37.get();if(cnd(_39,f_v)){n_v=_39+toAdd;if(!cnd(f_v,n_v)){_37.set(n_v);var _3a=20;window.setTimeout(function(){_38();},_3a);}else{_37.set(f_v);_2d=null;_2c.state=_state;if(typeof _2c.onCompleteCallback=="function"){_2c.onCompleteCallback();}}}};_38();}
fIOE._name="fade";fIOE._minimum=0.01;fIOE._maximum=1;fIOE._time=10;fIOE._step=0.08;function sIOE(_3b){var _3c=this;if(typeof _3c.onStartCallback=="function"){_3c.onStartCallback();}
var _3d=_3c.relation;var _3e=_3c.target;if(typeof _3c.orig=="undefined"){_3c.orig={};}
var _3f=_3c.orig.rel_box||(_3c.orig.rel_box=getLayout(_3d));var _40=_3c.orig.targ_box||(_3c.orig.targ_box=getLayout(_3e));var _41=_3c.orig.disp_delta||(_3c.orig.disp_delta=gBD(_3f,_40));var _42=_3c.orig.slide_dir||(_3c.orig.slide_dir=(Math.abs(_41.x)>Math.abs(_41.y))?"horz":"vert");var _43="rect("+_40.height+"px "+_40.width+"px "+_40.height+"px "+_40.width+"px"+")";_3e.style.clip=_43;var _44=_3c.config.base_step;var _45,f_v,cnd,toAdd,_state;if(_3b){_45=_3c.config.lowest_val+_44;f_v=_3c.config.h_v;cnd=function(a,b){return(a<b)?true:false;};toAdd=_44;_state=1;}else{_45=_3c.config.h_v-_44;f_v=_3c.config.lowest_val+_44;cnd=function(a,b){return(a>b)?true:false;};toAdd=(-1)*_44;_state=-1;}
var _4a=function(){this.target=_3e;};_4a.prototype.get=function(){var _4b=gCP(_3e,"clip");var _4c=_4b.match(/\d{1,4}px/g);if(_42=="vert"){var _4d=parseInt(_4c[0]);var _4e=Math.round((_4d*100)/_40.height);}else{var _4f=parseInt(_4c[3]);var _4e=Math.round((_4f*100)/_40.width);}
_4e=100-_4e;var _50=_4e/100;return _50;};_4a.prototype.set=function(_51){var _52=100-(Math.round(_51*100));if(_42=="vert"){var _53=Math.round((_52*_40.height)/100);var _54="rect("+_53+"px "+_40.width+"px "+_40.height+"px "+"0px"+")";_3e.style.clip=_54;_3e.style.marginTop=((-1)*_53)+"px";}else{var _55=Math.round((_52*_40.width)/100);var _54="rect("+"0px "+_40.width+"px "+_40.height+"px "+_55+"px"+")";_3e.style.clip=_54;_3e.style.marginLeft=((-1)*_55)+"px";}};var _56=new _4a();var _57=function(){if(!_3c.run){return;}
var _58=_56.get();if(cnd(_58,f_v)){n_v=_58+toAdd;if(!cnd(f_v,n_v)){_56.set(n_v);if(n_v>=f_v){_3e.style.clip="rect(0px 1000px 1000px 0px)";_3e.style.marginTop="0px";_3e.style.marginLeft="0px";_3e=null;_3c.state=_state;if(typeof _3c.onCompleteCallback=="function"){_3c.onCompleteCallback();}
return;}
var _59=10;window.setTimeout(function(){_57();},_59);}else{_3e.style.clip="rect(0px 1000px 1000px 0px)";_3e.style.marginTop="0px";_3e.style.marginLeft="0px";_3e=null;_3c.state=_state;}}else{_3e.style.clip="rect(0px 1000px 1000px 0px)";_3e.style.marginTop="0px";_3e.style.marginLeft="0px";_3e=null;_3c.state=_state;}};_57();}
sIOE._name="fade";sIOE._minimum=0.01;sIOE._maximum=1;sIOE._time=10;sIOE._step=0.08;